// <auto-generated />
namespace DeerflyPatches.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WebImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebImage));
        
        string IMigrationMetadata.Id
        {
            get { return "201711040330572_WebImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
