// <auto-generated />
namespace Deerfly_Patches.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testimonials1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testimonials1));
        
        string IMigrationMetadata.Id
        {
            get { return "201708291726240_testimonials1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
