// <auto-generated />
namespace DeerflyPatches.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201802151849545_FixCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
